// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2gICX9OLdWFQnLgFsjMB7ZUpjPwV0e4E',
    appId: '1:834336712270:web:5b1a6b6f42a619432d851f',
    messagingSenderId: '834336712270',
    projectId: 'spiritualwelfare',
    authDomain: 'spiritualwelfare.firebaseapp.com',
    storageBucket: 'spiritualwelfare.appspot.com',
    measurementId: 'G-TQQY2R7KMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX8ayyUfFXhQUB4fb6wBA7W9I7hexEOOA',
    appId: '1:834336712270:android:373ca437bd335dc42d851f',
    messagingSenderId: '834336712270',
    projectId: 'spiritualwelfare',
    storageBucket: 'spiritualwelfare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFy5JERek0IHKbgJSgSl6XwBPfCvt61Xs',
    appId: '1:834336712270:ios:ce0c0674151790962d851f',
    messagingSenderId: '834336712270',
    projectId: 'spiritualwelfare',
    storageBucket: 'spiritualwelfare.appspot.com',
    iosClientId:
        '834336712270-aflmo19e28cp61ljo2ma39l0vhftb2q1.apps.googleusercontent.com',
    iosBundleId: 'com.cycrosoft.spiritualwelfare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFy5JERek0IHKbgJSgSl6XwBPfCvt61Xs',
    appId: '1:834336712270:ios:ce0c0674151790962d851f',
    messagingSenderId: '834336712270',
    projectId: 'spiritualwelfare',
    storageBucket: 'spiritualwelfare.appspot.com',
    iosClientId:
        '834336712270-aflmo19e28cp61ljo2ma39l0vhftb2q1.apps.googleusercontent.com',
    iosBundleId: 'com.cycrosoft.spiritualwelfare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2gICX9OLdWFQnLgFsjMB7ZUpjPwV0e4E',
    appId: '1:834336712270:web:8720fb8779a34de22d851f',
    messagingSenderId: '834336712270',
    projectId: 'spiritualwelfare',
    authDomain: 'spiritualwelfare.firebaseapp.com',
    storageBucket: 'spiritualwelfare.appspot.com',
    measurementId: 'G-TQFN0XQYF3',
  );
}
