name: start
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0-0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_ui_auth: ^1.15.0
  firebase_ui_oauth_google: ^1.3.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  speech_to_text: ^6.6.2
  file_picker: ^8.0.7
  gradient_borders: ^1.0.0
  google_generative_ai: ^0.2.2
  flutter_markdown: ^0.7.3+1
  web: ^0.5.1
  test_api: ^0.7.2
  string_scanner: ^1.2.0
  url_launcher: ^6.3.0
  intl: ^0.19.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
cloud_firestore: ^5.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
